name: CMake CI
on: [push, pull_request]

jobs:
  build:
    runs-on: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: CMake
      run: cmake -DCMAKE_BUILD_TYPE=Debug CMakeLists.txt
    - name: make
      run: make
