name: CMake CI

on: [push, pull_request]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cmake -DCMAKE_BUILD_TYPE=Debug .
    - name: build
      run: make
